// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiM21nzNvQlMgJzivCqPBcnLk_GNMzWRg',
    appId: '1:222500889289:web:6303a34b0058bfa1e62318',
    messagingSenderId: '222500889289',
    projectId: 'safepulse-5b336',
    authDomain: 'safepulse-5b336.firebaseapp.com',
    storageBucket: 'safepulse-5b336.firebasestorage.app',
    measurementId: 'G-PJMNCZ7J85',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD738v9PDTVxXTySpQ8bXELzenENI9k34',
    appId: '1:222500889289:android:c8d14842a27b0423e62318',
    messagingSenderId: '222500889289',
    projectId: 'safepulse-5b336',
    storageBucket: 'safepulse-5b336.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTSKArWIrxTF8dRy_gCFY_TbVubQaR_0c',
    appId: '1:222500889289:ios:c14b969eb064b99be62318',
    messagingSenderId: '222500889289',
    projectId: 'safepulse-5b336',
    storageBucket: 'safepulse-5b336.firebasestorage.app',
    iosBundleId: 'com.example.safepulse',
  );

}